if(NOT DEFINED TEST_BINARY OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "TEST_BINARY and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
configure_file("${TEST_BINARY}" "${TEST_DIR}/plantuml_tests.exe" COPYONLY)
file(WRITE "${TEST_DIR}/settings.ini" "; Isolated plantuml test configuration\n")
set(test_args --portable-test)
if(DEFINED TEST_ARGS AND NOT "${TEST_ARGS}" STREQUAL "")
    list(APPEND test_args "${TEST_ARGS}")
endif()
execute_process(COMMAND "${TEST_DIR}/plantuml_tests.exe" ${test_args}
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Portable PlantUML test failed: ${result}")
endif()